### ISSUE TITLE
CreamInstaller isn't work with the new Cities Skyline update

### ISSUE THREAD

**Issue by Kamouse** [pointfeev/CreamInstaller#109]
Hi, the new cities skyline update has added 4 new DLC and Cream Installer can't install the DLC and doesn't unlock the previous DLC 
So, i don't have my previous and the new.. 
please help me :(.
Kamouse

**Comment by pointfeev** [comment]
Please read the last sentence of the [bold message below Usage instructions](https://github.com/pointfeev/CreamInstaller#note-this-program-does-not-automatically-download-nor-install-actual-dlc-files-for-you-as-the-title-of-the-program-states-this-program-is-only-a-dlc-unlocker-installer-should-the-game-you-wish-to-unlock-dlc-for-not-already-come-with-the-dlcs-installed-as-is-the-case-with-a-good-majority-of-games-you-must-find-download-and-install-those-to-the-game-yourself-this-process-includes-manually-installing-new-dlcs-and-manually-updating-the-previously-manually-installed-dlcs-after-game-updates) as I've just updated it, that probably addresses your problem. If it doesn't, then refer to the [cs.rin.ru](https://cs.rin.ru/forum/viewforum.php?f=10) post for Cities: Skylines because this isn't the place for this kind of issue.
