### ISSUE TITLE
Unstable, keeps crashing [12tb of games]

### ISSUE THREAD

**Issue by Chaython** [pointfeev/CreamInstaller#11]
Unstable, keeps crashing [12tb of games]
Should add options like directories to scan etc, rather than the whole system

**Comment by pointfeev** [comment]
Crashing how? Too much CPU usage, RAM usage, impatience perhaps?

It doesn't scan the whole system, it uses the registry to find steam's and epic's game directories, then searches those games' directories for the right DLL files needed for CreamAPI or ScreamAPI installation.

It should be very stable unless you have insignificant amounts of RAM or a less-powerful CPU, but I need to know which is the case to fix it.

I'd appreciate if you could use Task Manager or whatever you prefer to figure out the actual issue. :)

**Comment by Chaython** [comment]
I have a 10900f / 2x16gb 2933mhz memory....
It just crashes after like 30m... Only 10 games in the list at most. It also didn't do any form of caching to remember those games or scanned directories.
Also most steam games don't write to registry the install location, especially if you use a portable library. Rather, library folder should be user directed and .ACF files should be queiried?

**Comment by pointfeev** [comment]
Yes the program uses all of the VDF and ACF files throughout Steam's directories to end up with all the games' directories. By registry I meant it first finds Steam's install directory to begin finding the VDF/ACF files. The only time the program will be searching through "random" directories is to find steam_api.dll/EOSSDK-Win64-Shipping.dll/etc. etc.

I'm not sure why it would crash. Your specs are obviously fine, but could you check Task Manager to see if the program is going crazy on too much CPU or RAM usage perhaps? Does the program just outright crash and shut down, are there exceptions arising before it shuts down, or are you clicking it and telling Windows to shut it down when it "idles" for too long?

The program should be caching data it finds in "C:\ProgramData\CreamInstaller\appinfo," are you saying nothing is popping up in that directory? You should see json and VDF files there from Steam Store queries and SteamCMD parsing respectively.

**Comment by Chaython** [comment]
![image](https://user-images.githubusercontent.com/6486343/158163322-331be1fd-81fa-4ceb-9cc7-cb45fe4c1647.png)

**Comment by pointfeev** [comment]
Those SteamCMDs are from the program utilizing SteamCMD to gather DLC that normal steam store querying doesn't reveal, and for every SteamCMD process exists a console process (conhost.exe) due to SteamCMD being a console program. SteamCMD is limited currently to 20 processes, which means there should only be around 20 steamcmd.exe and 20 conhost.exe, maybe 2-3 more at most not counting other programs on your PC that require conhost.exe of course.

That 20 SteamCMD process limit has worked very well for me personally with a 10900K very similar to your 10900F, and nobody seems to have reported anymore SteamCMD issues since I added that limit. However, normal people obviously don't have 12 TB of games installed, so I'm gonna need to figure out what's going wrong with that. I'm going to try and simulate that circumstance on my own machine and see what I can find out. Sorry for the inconvenience! :)

**Comment by pointfeev** [comment]
Alright I've just released v3.3.0.0 which adds a bunch of Thread.Sleep statements in multiple locations throughout the code to hopefully help prevent CPU overload program crashes. Assuming that doesn't help, in this version I've also spent the past 8 hours adding a new pre-scan program/game selection dialog, so you can now choose which games the program will do the expensive scanning on:

![image](https://user-images.githubusercontent.com/15071274/158355556-d5888f9a-d107-4725-b34e-e7f9f3ca65fe.png)

In other news, I did a bunch of testing mostly consisting of for loops that add tons of fake games and DLC but with real directories and shit, and after the addition of the Thread.Sleep statements in multiple key areas, the program was entirely stable for me. My testing consisted of up to 500 games and 1200 DLC at one point, and while CPU usage got pretty high (up to 97% mostly, sometimes 100%), the program never crashed or ceased up. I can try to look into it further if this update isn't satisfactory however! :)

**Comment by pointfeev** [comment]
It's been nearly a month now so I'm going to assume this is no longer a relevant issue from the multiple changes.
