### ISSUE TITLE
how to unlock all DLC on macbookpro M1

### ISSUE THREAD

**Issue by xanto521** [pointfeev/CreamInstaller#111]
Hello, how to unlock all DLC on macbookpro M1, I found an article, but I couldn't find the files used by players in the article. activated.ini and libsteam_api.dylib these two files.

the url is 
https://www.reddit.com/r/Piracy/comments/9iui2p/using_creamapi_on_mac_for_cities_skylines_dlc/

thanks!

**Comment by pointfeev** [comment]
No idea, this program doesn't support macs and never will.

**Comment by xanto521** [comment]
ok, thank you for your reply.

**Comment by stanislavleonchik** [comment]
I found a way to activate the DLC on a macOS. The only problem is I can't crack the launcher. Its structure is different from the structure on Windows. Because of this, there is no connection with the Steam servers in the game: no servers are visible, there are no steam cloud saves.

https://disk.yandex.ru/d/C7JHH7k2yCX_Ng
Files to extract
