### ISSUE TITLE
CreamInstaller no longer opens after attempting to generate dlcs, dlcs unlocked in weird way

### ISSUE THREAD

**Issue by Futurecity10** [pointfeev/CreamInstaller#117]
Downloaded the CreamInstaller and ran it.  I tried to unlock all the DLCs for Total War Warhammer 1 but the game wouldnt launch after unlocking the dlcs, nor would the creaminstaller launch again.  I deleted the game then reinstalled it which somehow unlocked all the dlcs so I dont know how that happened.  However the Creaminstaller will still not run.

**Comment by pointfeev** [comment]
Steam uninstalling games doesn't delete the game directory, so anything not installed by Steam/the game (such as files installed by this program) are not deleted during uninstall. Otherwise, this is not the place for game specific issues, read the README. For the program not launching after, try checking your task manager to make sure it isn't somehow running in the background (no reason it should be, but WinForms could be messing up there), restart your computer if that doesn't work or you can't figure that out, and finally just try reinstalling following the instructions (mind the note under installation) in the README should those not fix it.
