### ISSUE TITLE
NativeAOT

### ISSUE THREAD

**Issue by Mochongli** [pointfeev/CreamInstaller#14]
Use NativeAOT?

**Comment by pointfeev** [comment]
> Use NativeAOT?

I'm unfamiliar with NativeAOT, what are the benefits of using it over a self-contained application like I am now? I've tried a bunch of research but I can't find an answer to that question.

**Comment by pointfeev** [comment]
I've just done a bunch of testing and it's not looking good. NativeAOT doesn't support WinForms or ResourceManager at all, especially due to trimming. I followed [this](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/compiling.md) and even tried [this](https://codevision.medium.com/again-winforms-and-nativeaot-fd068425cc13) to no avail.
