### ISSUE TITLE
Stuck on setting up steamcmd

### ISSUE THREAD

**Issue by FallToValhalla** [pointfeev/CreamInstaller#144]
When I click ok on the game I want to unlock the dlc for, it loads to setting up steamcmd and stops at 0%. I've tried resetting the program as well as my computer a few times, in addition to leaving it running over night to see if any progress was made (none was).

**Comment by Thman558** [comment]
Close the steam application fully through task manager

**Comment by pointfeev** [comment]
This would likely be due to some networking issues on your part or on Steam's part, of which I can't really do anything about except advise trying a VPN temporarily or something similar to isolate the issue. See #121 where it was fixed simply with a program or computer restart, even though you said you already tried that.

**Comment by ZonaiCat777** [comment]
Go to the files of the app and find steamCMD.exe open it and update it then relaunch creaminstaller
