### ISSUE TITLE
Fixed or patched by RimWorld

### ISSUE THREAD

**Issue by Rezanans-wow** [pointfeev/CreamInstaller#15]
###### Describe the bug and/or provide an image of the exception dialog box:
Hello, yesterday i updated RimWorld and seen patch got removed. I downloaded new version of Cream installer but when me start, i seen Unity Crash Reporter and game not want start (Crash)

Old versions same result. Can its get fixed? Because only with CreamInstaller DLC work

**Comment by HuscurlSquirrel** [comment]
Simple fix. Go to your Rimworld installation folder and find "\RimWorldWin64_Data\Plugins". Add "extraprotection = true" underneath the "appid =" in the "[steam]" section. Should be quick and easy for the maker of this to fix as well.

**Comment by pointfeev** [comment]
I've just conducted testing with extraprotection and my game doesn't go past a black screen with or without that option, so adding it would do nothing. I have yet to add extraprotection toggling ability because I've yet to personally see any game benefit from it, since most games with "extra protection" won't work regardless of that settings due to using EasyAntiCheat or BattlEye.

Regardless, from information on the rin, it would seem as though you should not be using CreamAPI on RimWorld in the first place, and there is a much easier method of unlocking DLC for legit users. See [here](https://cs.rin.ru/forum/viewtopic.php?p=2446372#p2446372) and [here](https://cs.rin.ru/forum/viewtopic.php?p=2543447#p2543447). I would recommend always going to appropriate rin topics for the games you wanna use this tool on, because as I emphasize in the description, CreamAPI and ScreamAPI are not tested for every game.
