### ISSUE TITLE
Sort order of detected games

### ISSUE THREAD

**Issue by xADDBx** [pointfeev/CreamInstaller#19]
Upon launching the tool the detected games will be displayed by order of their AppIDs. I do think that isn't really intuitive, as you're more than likely to look for a game with a specific name instead of one with a specific AppID, and not many people would have them memorized. So I think making standard/offering the possibility to sort by Name would be an appreciated enhancement.

**Comment by pointfeev** [comment]
Well it's sorted by AppIDs because it's in that order in which they'll go into the CreamAPI/ScreamAPI config files. Everything, including the display, goes through a single sort method at the moment.

I can definitely add some way to switch to alphabetic sorting, though I'm thinking at the moment that it will likely only be in the form of a checkbox or button in the pre-scan dialog box only. I don't believe the selection form itself would really need such a feature, considering you should really only be choosing games in the pre-scan dialog box that you intend on cracking (probably all) DLC for.

**Comment by pointfeev** [comment]
You'll be able to choose to sort by names in the pre-scan dialog box in v3.5.2.0! I likely won't be adding such a feature to the actual selection form, however.

**Comment by pointfeev** [comment]
Sike, just added it to the main selection form as well in v3.6.0.0+!
