### ISSUE TITLE
Support for folders on other disks

### ISSUE THREAD

**Issue by cevassil** [pointfeev/CreamInstaller#21]
Maybe add some kind of support e.g. manual folder selection in case games are installed somewhere other than the default installation folder. I got most of my steam games on a second disk and they don't get detected by default.

**Comment by pointfeev** [comment]
I'll definitely consider adding this functionality, likely with a button or something similar on the pre-scan dialog.

**Comment by pointfeev** [comment]
What exactly do you mean by "somewhere other than the default installation folder"? I ask this because the program right now searches every directory connected with Steam through the use of the multiple VDF and ACF files scattered throughout its directories. This means if a game is properly installed and set up within Steam, it should always be detected. Thus, I need a bit more of an explanation as to how the games that aren't getting detected on your system are installed.

**Comment by cevassil** [comment]
Yesterday when I used it a couple of games didn't show up. It's working fine now. Installation folder was created within steam.
