### ISSUE TITLE
Arma 3

### ISSUE THREAD

**Issue by Kentainfr** [pointfeev/CreamInstaller#27]
###### Describe the bug and/or provide an image of the exception dialog box:

Game: Arma 3

Issue: Can't use mods, or check dlc on the launcher. 

Error : Initializing of steam service.

Tried to uninstall and it work but when I install it back it broke again.

**Comment by Kentainfr** [comment]
I got it fixed. Did use the cream api from unknown cheat and edited few stuff out. Added the files to launcher & Main directory and work like a charm.

https://i.imgur.com/ZOARFSu.png
https://i.imgur.com/3O4kktV.png

Here is proof it works and here is the file I have used
[CreamAPI Arma 3.zip](https://github.com/pointfeev/CreamInstaller/files/8721198/CreamAPI.Arma.3.zip)

Picture of the interior of the zip : https://i.imgur.com/fyAvBrW.png

**Comment by Kentainfr** [comment]
Maybe add this files I have send above so you can do like Cities Skylines

Arma 3 & Arma 3 launcher installation

**Comment by pointfeev** [comment]
Interesting, please refer this issue to acidicoala (developer of SmokeAPI) [here](https://cs.rin.ru/forum/viewtopic.php?f=29&t=122487) instead.

I will not be switching the program back to CreamAPI; CreamAPI is very outdated (which is why it no longer works on RimWorld) and now entirely unmaintained as of the release of SmokeAPI.

**Comment by Kentainfr** [comment]
Alright will do. Thank you for your time ! Take care.
