### ISSUE TITLE
Game Detections Window Freeze

### ISSUE THREAD

**Issue by Kentainfr** [pointfeev/CreamInstaller#3]
When the game are detected and try to move the windows it freeze and can't do nothing.

**Comment by Kentainfr** [comment]
It even freeze the whole pc out.

**Comment by pointfeev** [comment]
I'm assuming your PC has a lower-end CPU and/or RAM? This likely occurs due to the amount of SteamCMD windows that will open when the program is gathering AppInfo for all the installed games and their DLC. I'm going to experiment with limiting these windows while also maintaining the speed of gathering to fix this issue. :)

**Comment by pointfeev** [comment]
I've released v2.2.4.0 in an attempt to address this issue, please tell me if it fixes it or at the very least helped!

**Comment by pointfeev** [comment]
I've just added a SteamCMD process limit of 20, drastically reducing CPU usage without sacrificing speed. Thus, since it's been 3 weeks with no response, I'm going to go ahead and close this issue.
