### ISSUE TITLE
False Positive?

### ISSUE THREAD

**Issue by Disretired** [pointfeev/CreamInstaller#40]
Since the 4.0.0.0 update, the version.dll it puts in is being detected by all common antivirus software's as a trojan, only started upon the addition of KOALoader, I'm guessing false positive, but I know this will still spook many paranoid users.

**Comment by pointfeev** [comment]
Yes, all of Koaloader's DLLs will be flagged as trojans, as is the very nature of Koaloader. Of course it's a false positive, but if you don't trust it then by all means feel free to test the MD5s and such to make sure they're the real Koaloader [here](https://github.com/pointfeev/CreamInstaller/tree/main/CreamInstaller/Resources/Koaloader), and/or even go as far as to build Koaloader and/or this program yourself lol.

**Comment by t3rry327** [comment]
kids are really annoying with this, just, if you don't want to install this then just buy the dlc and stop trash talking

**Comment by waltzforvenus** [comment]
ummm... why not release a github action to automatically build both the software and koloader instead of providing the binary manually? that way it would clear out people's minds about the software containing any sort of malware without them (non-technical-users) having to manually build it and the technical users can actually assess that the binaries are generated in a legit way to assure others.

**Comment by juantote04** [comment]
genuine question: virustotal detected version.dll as a malware on 44 AVs. I'm trying to not think too much about it because I know these stuff is generally safe, but 44 warnings is a bit too much for me. Is there any reason why so many AVs consider it a malware?I'm really new at this. Maybe It's just a false positive and a very generic result, but still. 

Also, does creaminstaller use the same files that cs dot rin uses?

Virus Total Link:
https://www.virustotal.com/gui/file/2665a951793eac577c89d9115aff15b3c69f87af4da15a93a81200c890a4cd00/detection

**Comment by globalista-dev** [comment]
@juantote04 There are dozens of closed issues (including this one) that address exactly what you're asking. You should've read the README (it's called read me for a reason), because it's literally in the FAQ. Or you could open Koaloader's page on cs.rin.ru. Or you could check all those issue reports. If for some unknown reason you're still not comfortable, just don't download this and install CreamAPI yourself, I guess.
