### ISSUE TITLE
Introducing special workarounds for games with edge case dlc

### ISSUE THREAD

**Issue by xADDBx** [pointfeev/CreamInstaller#60]
I honestly don't know if it's actually wort the hassle to implement, but certain games don't would need special treatment to get all their dlcs unlocked. An example would be Total War: Warhammer 3. It includes a sandbox like mode where all content from the game, the dlcs and its two predecessors + their dlcs can be used - as long as they are unlocked. Meaning, complete dlc unlocking would not only need dlcs of the third game, but also the dlcs and base game of its predecessors.

Here's how a complete list for a TTW3 unlock would look like:

364360 = Total War: WARHAMMER
404010 = Total War: WARHAMMER - Chaos Warriors
{more TTW1 dlcs}
594570 = Total War: WARHAMMER II
594590 = Total War: WARHAMMER II - Chaos Warriors Race Pack
{more TTW2 dlcs}
1374300 = Total War: WARHAMMER III - Blood for the Blood God III
{more TTW3 dlcs}

The current version would instead only list all TTW3 dlcs. 
I'm honestly unsure if implementing this is really useful since I can't think of any other way than manually adding workarounds for every game that needs this treatment (feel free to correct me if there's actually a way to do this automatically), which would be tedious work and just make the code more ugly. I just thought it was worth a mention that exceptions like this existed.

And I may be misremembering, but wasn't there an option to try and unlock all dlcs? Does SmokeAPI just not offer that functionality or is my memory tricking me here?

**Comment by pointfeev** [comment]
That is certainly interesting, I'd have to look into Warhammer III's Steam CMD and Store outputs to see if automation really is possible for that case, I'm not sure. Otherwise, it's such an edge case that I might just add an exception in the code for it.

Regarding ScreamAPI, yes it should automatically unlock DLC, and this app configures it to do so; the point of the DLC selections is to exclude some DLC if you desire, therefore. It's also to automatically exclude certain unknown (nameless, page-less, usually harmful or bloating) DLC. You should take a look into either the code or the config output if you're curious further on how the app does it.

ScreamAPI may very well not automatically unlock completely separate games' DLC unless listed in the config, as that would likely also be an edge case for it as well.

**Comment by pointfeev** [comment]
The queries to the Steam Store and/or SteamCMD actually already include the DLCs from the previous titles in it for TTW3, so all I had to do was make sure it would also include the games as well (in v4.7.0.0). You'll have to let me know if SmokeAPI doesn't automatically handle that, because I can always force generate the config file should it detect it necessary.
