### ISSUE TITLE
trojan?

### ISSUE THREAD

**Issue by redkurn** [pointfeev/CreamInstaller#9]
###### Describe the bug and/or provide an image of the exception dialog box:
https://www.virustotal.com/gui/file/eaf45b0ed5a1affd64498fb58ac467a027cca0e2ea96b288d56fdabeeef06b26?nocache=1

what's the deal with that and why is this an exe when the forum linked downloads dll files?

**Comment by pointfeev** [comment]
Apparently it's a trojan because "[it performs some HTTP requests](https://howtofix.guide/trojan-psw-win32-disco/)." That is likely due to this program looking up GitHub changelogs when an update is available. The entire source code of this project is available, so if you're scared feel free to have your own gander at what it really does.

As for why it shows a DLL, that's because this program is a "[single file application](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file)" which basically means that Windows will handle all of the components of it; as in, when you open the program for the first time it will "extract" all of the files for the program into a temp folder (I think somewhere in AppData). The DLL file you see is the main bulk of the program.

**Comment by pointfeev** [comment]
Also, what do you mean by "when the forum linked downloads DLL files?" That's literally what CreamAPI is, this project is just a program that automates it. You should also note that the DLL files from that forum is already embedded into the program.

**Comment by pointfeev** [comment]
It could be due to the program [grabbing and caching icons from websites to use for the right-click context menu](https://github.com/pointfeev/CreamInstaller/blob/main/CreamInstaller/Classes/ProgramSelection.cs)? That's about the only other reason I could give for it. I know a long time ago I did a VirusTotal on it just for curiosity and it was clean. Anyways, I'll go ahead and close this issue. I'll see if there's some way to get rid of that false-positive (there probably isn't).
